import type { ThemeManifest, RoleColors } from "./types";

const BASE_ROLES: RoleColors = {
  background: "#FFFFFF",
  title: "#111827",
  bold: "#111827",
  decoration: "#059669",
  divider: "#D1D5DB",
  list: "#059669",
  code: "#059669",
  table: "#059669",
  inlineText: "#059669",
  inlineShadow: "#ECFDF5",
  quote: "#059669",
};

export const THEMES: ThemeManifest[] = [
  {
    id: "moyu-green",
    name: "摸鱼绿",
    en: "moyu-green",
    scene: "教程、测评、清单、工具盘点",
    pageBg: "#F0FDF4",
    paper: "#FFFFFF",
    ink: "#111827",
    text: "#374151",
    muted: "#6B7280",
    accent: "#059669",
    accentOn: "#FFFFFF",
    soft: "#ECFDF5",
    softBorder: "#A7F3D0",
    divider: "#D1D5DB",
    underlineCss: "border-bottom:2px solid #A7F3D0;font-weight:600;",
    titleFont:
      "-apple-system,BlinkMacSystemFont,'PingFang SC','Hiragino Sans GB','Microsoft YaHei',sans-serif",
    bodyFont:
      "-apple-system,BlinkMacSystemFont,'PingFang SC','Hiragino Sans GB','Microsoft YaHei',sans-serif",
    bodySize: 15,
    lineHeight: 1.8,
    letterSpacing: "0.5px",
    radius: 10,
    shadow: "0 6px 18px rgba(5,150,105,.10)",
    roles: { ...BASE_ROLES, decoration: "#059669", list: "#059669" },
    posterAccent: "#059669",
  },
  {
    id: "red-white",
    name: "红白色系",
    en: "red-white",
    scene: "深度分析、观点、力量感话题",
    pageBg: "#FEF2F2",
    paper: "#FFFFFF",
    ink: "#1C1917",
    text: "#374151",
    muted: "#9CA3AF",
    accent: "#DC2626",
    accentOn: "#FFFFFF",
    soft: "#FEF2F2",
    softBorder: "#FECACA",
    divider: "#E5E7EB",
    underlineCss: "border-bottom:2px solid #FECACA;font-weight:600;",
    titleFont:
      "-apple-system,BlinkMacSystemFont,'PingFang SC','Hiragino Sans GB','Microsoft YaHei',sans-serif",
    bodyFont:
      "-apple-system,BlinkMacSystemFont,'PingFang SC','Hiragino Sans GB','Microsoft YaHei',sans-serif",
    bodySize: 15,
    lineHeight: 1.8,
    letterSpacing: "0.5px",
    radius: 8,
    shadow: "0 6px 18px rgba(220,38,38,.08)",
    roles: { ...BASE_ROLES, decoration: "#DC2626", list: "#DC2626" },
    posterAccent: "#DC2626",
  },
  {
    id: "graphite-minimal",
    name: "石墨极简风",
    en: "graphite-minimal",
    scene: "设计、科技评论、专业观点、高端品牌",
    pageBg: "#FAFAFA",
    paper: "#FFFFFF",
    ink: "#27272A",
    text: "#3F3F46",
    muted: "#A1A1AA",
    accent: "#52525B",
    accentOn: "#FFFFFF",
    soft: "#FAFAFA",
    softBorder: "#E4E4E7",
    divider: "#E4E4E7",
    underlineCss: "border-bottom:2px solid #52525B;font-weight:600;",
    titleFont:
      "-apple-system,BlinkMacSystemFont,'PingFang SC','Hiragino Sans GB','Microsoft YaHei',sans-serif",
    bodyFont:
      "-apple-system,BlinkMacSystemFont,'PingFang SC','Hiragino Sans GB','Microsoft YaHei',sans-serif",
    bodySize: 15,
    lineHeight: 1.8,
    letterSpacing: "0.3px",
    radius: 4,
    shadow: "0 1px 2px rgba(0,0,0,.04)",
    roles: { ...BASE_ROLES, decoration: "#52525B", list: "#52525B" },
    posterAccent: "#52525B",
  },
  {
    id: "zen-whitespace",
    name: "留白禅意风",
    en: "zen-whitespace",
    scene: "禅意冥想、极简生活、深度随笔、艺术留白",
    pageBg: "#FFFFFF",
    paper: "#FFFFFF",
    ink: "#2B2B2B",
    text: "#525252",
    muted: "#A3A3A3",
    accent: "#4A5D52",
    accentOn: "#FFFFFF",
    soft: "#EEF3F0",
    softBorder: "#D6E4DC",
    divider: "#E8E8E8",
    underlineCss: "border-bottom:1.5px solid #B5C8BC;font-weight:500;",
    titleFont: "'Noto Serif SC',Georgia,'Times New Roman',serif",
    bodyFont:
      "-apple-system,BlinkMacSystemFont,'PingFang SC','Hiragino Sans GB','Microsoft YaHei',sans-serif",
    bodySize: 15,
    lineHeight: 1.9,
    letterSpacing: "0.3px",
    radius: 2,
    shadow: "none",
    roles: { ...BASE_ROLES, decoration: "#4A5D52", list: "#4A5D52" },
    posterAccent: "#4A5D52",
  },
  {
    id: "moyu-ticket",
    name: "摸鱼票据风",
    en: "moyu-ticket",
    scene: "测评、工具对比、创意评测",
    pageBg: "#fffef8",
    paper: "#fffef8",
    ink: "#1a1a1a",
    text: "#555555",
    muted: "#888888",
    accent: "#059669",
    accentOn: "#FFFFFF",
    soft: "#F0FDF4",
    softBorder: "#A7F3D0",
    divider: "#E5E7EB",
    underlineCss: "border-bottom:2px solid #A7F3D0;font-weight:600;",
    titleFont:
      "-apple-system,BlinkMacSystemFont,'PingFang SC','Hiragino Sans GB','Microsoft YaHei',sans-serif",
    bodyFont:
      "-apple-system,BlinkMacSystemFont,'PingFang SC','Hiragino Sans GB','Microsoft YaHei',sans-serif",
    bodySize: 14,
    lineHeight: 1.9,
    letterSpacing: "0.5px",
    radius: 6,
    shadow: "6px 6px 0 rgba(26,26,26,.9)",
    roles: { ...BASE_ROLES, decoration: "#059669", list: "#059669" },
    posterAccent: "#059669",
  },
  {
    id: "olive-journal",
    name: "橄榄手记",
    en: "olive-journal",
    scene: "内刊手记、深度评测、案例复盘",
    pageBg: "#fdfdf8",
    paper: "#fdfdf8",
    ink: "#1e1f23",
    text: "#4d4f46",
    muted: "#9ea096",
    accent: "#ed7b2f",
    accentOn: "#FFFFFF",
    soft: "#eeefe9",
    softBorder: "#bfc1b7",
    divider: "#bfc1b7",
    underlineCss: "border-bottom:2px solid #ed7b2f;font-weight:600;",
    titleFont:
      "-apple-system,BlinkMacSystemFont,'PingFang SC','Hiragino Sans GB','Microsoft YaHei',sans-serif",
    bodyFont:
      "-apple-system,BlinkMacSystemFont,'PingFang SC','Hiragino Sans GB','Microsoft YaHei',sans-serif",
    bodySize: 14,
    lineHeight: 1.9,
    letterSpacing: "0.3px",
    radius: 6,
    shadow: "0 1px 3px rgba(30,31,35,.08)",
    roles: { ...BASE_ROLES, decoration: "#ed7b2f", list: "#ed7b2f" },
    posterAccent: "#ed7b2f",
  },
  {
    id: "sentinel-dark",
    name: "哨兵深色",
    en: "sentinel-dark",
    scene: "AI 工具、科技向内容（中性预设）",
    pageBg: "#101418",
    paper: "#FFFFFF",
    ink: "#0f172a",
    text: "#334155",
    muted: "#64748b",
    accent: "#38bdf8",
    accentOn: "#082f49",
    soft: "#f0f9ff",
    softBorder: "#bae6fd",
    divider: "#e2e8f0",
    underlineCss: "border-bottom:2px solid #7dd3fc;font-weight:600;",
    titleFont:
      "-apple-system,BlinkMacSystemFont,'PingFang SC','Hiragino Sans GB','Microsoft YaHei',sans-serif",
    bodyFont:
      "-apple-system,BlinkMacSystemFont,'PingFang SC','Hiragino Sans GB','Microsoft YaHei',sans-serif",
    bodySize: 15,
    lineHeight: 1.8,
    letterSpacing: "0.3px",
    radius: 10,
    shadow: "0 6px 18px rgba(56,189,248,.12)",
    roles: { ...BASE_ROLES, decoration: "#38bdf8", list: "#38bdf8" },
    posterAccent: "#38bdf8",
  },
];

export function getTheme(id: string): ThemeManifest {
  return THEMES.find((t) => t.id === id) ?? THEMES[0];
}

export function themeWithRoles(
  theme: ThemeManifest,
  overrides: Partial<RoleColors>
): ThemeManifest {
  if (!overrides || Object.keys(overrides).length === 0) return theme;
  return { ...theme, roles: { ...theme.roles, ...overrides } };
}
